# Generated by Django 3.0.5 on 2020-05-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0002_auto_20200501_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message_room',
            name='user',
        ),
        migrations.AddField(
            model_name='message_room',
            name='users',
            field=models.ManyToManyField(to='Message.Persons'),
        ),
    ]
